// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImYhZJcrN1Nbcd23anejjIeDP7klzL9Q',
    appId: '1:151951069415:web:f9f75980c7969ec4a59242',
    messagingSenderId: '151951069415',
    projectId: 'chat-app-645bd',
    authDomain: 'chat-app-645bd.firebaseapp.com',
    storageBucket: 'chat-app-645bd.appspot.com',
    measurementId: 'G-8N50VYM38K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3XqhahrWvPH9vbmM5rw8BZznZKG7Siw',
    appId: '1:151951069415:android:619236cc6a486345a59242',
    messagingSenderId: '151951069415',
    projectId: 'chat-app-645bd',
    storageBucket: 'chat-app-645bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkNkvEGS4zBts6I0d9hupduAKxe_AUa_Q',
    appId: '1:151951069415:ios:78606217234799a5a59242',
    messagingSenderId: '151951069415',
    projectId: 'chat-app-645bd',
    storageBucket: 'chat-app-645bd.appspot.com',
    iosClientId: '151951069415-4u9ahqs03jfelbrtbq2g14334ensqjum.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkNkvEGS4zBts6I0d9hupduAKxe_AUa_Q',
    appId: '1:151951069415:ios:78606217234799a5a59242',
    messagingSenderId: '151951069415',
    projectId: 'chat-app-645bd',
    storageBucket: 'chat-app-645bd.appspot.com',
    iosClientId: '151951069415-4u9ahqs03jfelbrtbq2g14334ensqjum.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
